spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/employee_db}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:khak}

  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
